name: WebApp Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: fruocco
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker build . --file WebApp.Dockerfile --tag fruocco/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag fruocco/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER fruocco/oai-embeddings:latest;
        docker push fruocco/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push fruocco/oai-embeddings:latest;
        
